### ISSUE TITLE
getOutputFromHtml  - no images

### ISSUE THREAD

**Issue by gam6itko** [KnpLabs/snappy#104]
I have file.html, with content below

```
<div class="Logo">
    <img src="/assets/ui/logo-commoncore.svg">
</div>
```

I use code below to render pdf

```
    $fileContent = file_get_content('file.html');
    $snappy = new Pdf('wkhtmltopdf');
    header('Content-Type: application/pdf');
    return $snappy->getOutputFromHtml($fileContent );
```

The image `assets/ui/logo-commoncore.svg` is not apears

but if i add absolute url it will fix the problem

```
<div class="Logo">
    <img src="http://mysite.com/assets/ui/logo-commoncore.svg">
</div>
```

How i can avoid to add `sile_url` to any image <img> tag in page?
What is the native way to set path to images in php code ?

**Comment by jijoel** [comment]
I found that this worked well for all locally-hosted files, but if I used both local and remote files, (both relative and absolute addressing), it would fail. There's a pretty simple fix to it, though:

```php
$site_url = "{$_SERVER['REQUEST_SCHEME']}://{$_SERVER['HTTP_HOST']}";
$html = preg_replace('/(<img.*?src=")(?!http)(.*">)/',"$1$site_url/$2",$html);
```

**Comment by ingedgarmorales** [comment]
Hello. I found a very simple solution to fix this issue that have some people when they try to generate a PDF from HTML that contains remote images. 

Snappy uses the `Symfony\Component\Process\Process` class (if is available) or else use its own class `Knp\Snappy\Process.php`, in either case, the command to generate the PDF file uses the PHP function `proc_open`.

```php
// file: Knp\Snappy\AbstractGenerator.php

abstract class AbstractGenerator implements GeneratorInterface
{
    protected function executeCommand($command)
    {
        if (class_exists('Symfony\Component\Process\Process')) {
            $process = new \Symfony\Component\Process\Process($command, NULL, $this->env);
            if ($this->timeout !== false) {
                $process->setTimeout($this->timeout);
            }
        } else {
            $process = new Process($command, $this->env);
        }

        $process->run();
        
        return array(
            $process->getExitCode(),
            $process->getOutput(),
            $process->getErrorOutput(),
        );
    }
}
```

In both cases, snappy uses wkhtmltopdf extension and when you run a command of wkhtmltopdf using `proc_open` you are running in a child process and the reason the remote images are not rendering is because you need to specify the environment variables for the command line that will be run or use the current PHP environment.

The problem is in the value that has `$this->env`.  If this is an empty array PHP considers that there are no environment variables and does not use the current PHP environment, however if the value is NULL, PHP assigns as environment variables the same environment in the current PHP and this is that we have to do to generate PDF files correctly.

So the correction that I propose is to change the default value of the `$this->env` variable from empty array to NULL.

# Change the load configuration from the KnpSnappyBundle

```php
// file: knp-snappy-bundle\Knp\Bundle\SnappyBundle\DependencyInjection\KnpSnappyExtension.php

class KnpSnappyExtension extends Extension
{
    /**
     * {@inheritDoc}
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        /...
        
        if ($config['pdf']['enabled']) {
            // ...

            // find by:
            $container->setParameter('knp_snappy.pdf.env', $config['pdf']['env'] );
            // remplace to:
            $container->setParameter('knp_snappy.pdf.env', empty($config['pdf']['env']) ? null : $config['pdf']['env'] );
        }

        if ($config['image']['enabled']) {
            // ...

            // find by:
            $container->setParameter('knp_snappy.image.env', $config['image']['env'] );
            // remplace to:
            $container->setParameter('knp_snappy.image.env', empty($config['image']['env']) ? null : $config['image']['env']);
        }
    }
}
```

Now, if you run the command wkhtmltohtml from `\Symfony\Component\Process\Process` or `Knp\Snappy\Process.php`, your PDF files will be generated with the remote images rendered, 
and then the methods like `generateFromHtml` will be works fine.

**Comment by NiR-** [comment]
@ingedgarmorales I don't see how it could fix this issue... But it might help for other issues. Good catch!

Since wkhtmltopdf runs from the cli, it doesn't know how to resolve relative media URLs. Thus we need to use either absolute URLs, or use a `<base></base>` tag.

```html
<!DOCTYPE html>
<html>
  <head>
    <base href="https://github.com">
  </head>
  <body>
    <img src="fluidicon.png" />
  </body>
</html>
```
