### ISSUE TITLE
The process has been signaled with signal "11". error

### ISSUE THREAD

**Issue by fatstar** [KnpLabs/snappy#124]
I tried to use 1and1.com shared hosting.
When I use wkhtmltopdf-i386, I got 'The process has been signaled with signal "11".' error.
and I use wkhtmltopdf-amd64, I got
"The exit status code '127' says something went wrong: stderr: "sh: /homepages/xx/yyyyyyyy/htdocs/2space/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: No such file or directory " stdout: "" command: /homepages/xx/yyyyyyyy/htdocs/2space/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '20' --margin-left '15' --margin-right '15' --margin-top '20' --page-size 'A4' '/tmp/knp_snappy5463fb372bfbb1.29818575.html' 'public/onsiteuploads/19/onsite_14146413998Ym.pdf'." error
How can I fix this problem ?

I tried command line input as
wkhtmltopdf-amd64/bin >  wkhtmltopdf-amd64 google.com google.pdf
-bash: ./wkhtmltopdf-amd64: No such file or directory

wkhtmltopdf-i386/bin >  wkhtmltopdf-i386 google.com google.pdf
Segmentation fault

Thank you for your help.

**Comment by celvin** [comment]
could return the same error in centOS, because SeLinux

1. enable: Audit
# auditd

2.
# tail -F /var/log/audit/audit.log | grep wkhtml > wkhtml.audit  

 (leave this running and continue to next step) 

3. try to load your web page that attempts to create a pdf, it will fail as before but now we are logging. 
4. CTRL+C to stop the process from step 2 (can skip to 7 if in a hurry, but it's strongly suggested you use these review steps before making selinux exceptions permanent!) 
5. cat wkhtml.audit | audit2allow -m wkhtmltopdf > wkhtmltopdf.te 
6. review the wkhtmltopdf.te file to make sure new rules will be sensible. you will probably see "allow httpd_t self:process execmem" and possibly "allow httpd_t var_t:file read" depending on your setup 
7. cat wkhtml.audit | audit2allow -M wkhtmltopdf 
8. semodule -i wkhtmltopdf.pp (might take a minute, be patient)

**Comment by pusle** [comment]
I got this error on Centos 7, and tried @celvins solution but did not get any errors in the wkhtml.audit-file. To solve it temorary I did a `setsebool httpd_execmem on`. I have a feeling this is not the best solution, but why that is, I do not know.

**Comment by celvin** [comment]
what's the source of the package you have installed, its version, and where the binaries have been installed? CentOS 7 is now more careful about what is the SeLinux context for public folders, check this out https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-SELinux_Contexts_Labeling_Files-Persistent_Changes_semanage_fcontext.html

**Comment by pusle** [comment]
Sorry for the late reply @celvin. The version is `wkhtmltox-0.12.2.1_linux-centos7-amd64.rp`m, and I downloaded it from [http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/](http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/)

**Comment by pusle** [comment]
I read the redhat documentation, but I am afraid that is beyond me at this point.

**Comment by florianajir** [comment]
I have the same issue on centos7, is snappy dependencies taking care of which system is used ?
If I execute `composer require knplabs/knp-snappy` from a debian based docker and composer install on centos system is it smart enough to know which binary to use ? if not maybe my issue come from here but it's strange that on some documents it's working but not always.
