### ISSUE TITLE
Undefined variable $pipes in Process.php L59

### ISSUE THREAD

**Issue by cristianp6** [KnpLabs/snappy#150]
Hi,
I get this:
CRITICAL: Symfony\Component\Debug\Exception\ContextErrorException:
**Undefined variable: pipes** (uncaught exception)
at [/.../vendor/knplabs/knp-snappy/src/Knp/Snappy/Process.php](https://github.com/KnpLabs/snappy/blob/4d46c5d2229981a20c45570d044ef9d926431a9b/src/Knp/Snappy/Process.php#L59) line 59

From where $pipes came from?
How should be fixed?

Thanks!

**Comment by jeremyb** [comment]
Hi @cristianp6,

As you can see here http://php.net/proc_open the `$pipes` variable is passed as reference, so no need to create it before.

I think this issue is not related to Snappy (perhaps more to the symfony/debug component) but I've tried in my project and I don't get any errors.
I think you just need to update your vendors and it should work.

**Comment by akovalyov** [comment]
We are relying on Symfony/Process now, so this issue is not relevant anymore.
