### ISSUE TITLE
wkhtmltopdf-i386 not recognized 

### ISSUE THREAD

**Issue by retrogradeMT** [KnpLabs/snappy#156]
I am getting the error: 
 
    production.ERROR: exception 'RuntimeException' with message 'The exit status code '127' says something went wrong: stderr: "sh: 1: /home/forge/mysite.com/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: not found

however, when I 
  
    cd into mysite.com/vendor/h4cc/wkhtmltopdf-i386/bin  

I see the file wkhtmltopdf-i386.  

As suggested in another thread, I attempted to 

    run vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --version, 

from the base directory and got a "file not found"  error.   

I checked permissions, that isn't the issue.   Any idea how to fix this?

**Comment by akovalyov** [comment]
@retrogradeMT can you try ```./vendor/bin/wkhtmltopdf-i386``` ? It is symlinked in that dir (in your bin/dir as well if you have configured it). However, this issue is with that executable permissions on your server. As the package maintainer suggests, [In case this package does not work on your system, try installing the matching system packages from wkhtmltox website.](https://github.com/h4cc/wkhtmltopdf-i386#installation). Also, sometimes there are permissions issues if you use SELinux kernel.
