### ISSUE TITLE
Black background on transparent PNG's?

### ISSUE THREAD

**Issue by henrikromby** [KnpLabs/snappy#157]
Hello!

I have a PNG with a transparent background. In Chrome, it shows with a transparent background as expected. When generating a PDF, the background turns black. Is there some option or something that I am missing?

Thanks!

**Comment by akovalyov** [comment]
@henrikromby I am sorry, but this issue is not Snappy one, you should check wkhtmltopdf devs issue tracker, i.e. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2214

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by digitalmoran** [comment]
I am working on a project where using the 0.12.3 development release is not an option. After exploring the issue further, it appears to happen when the dpi of the PNG image is much higher than the dpi of the pdf. In my case the source PNG image was 300 dpi and the PDF was 96 dpi. When I changed the source image dpi to 150 or 96 the background is transparent as expected. On OSX I used: `sips -g all image.png` to see the image metadata like color profile, dpi, etc.
