### ISSUE TITLE
Temporary files are never deleted if an exception occurred

### ISSUE THREAD

**Issue by jeremyb** [KnpLabs/snappy#167]
Just a reminder, an issue to fix, I realised that `__destruct` is never called if an exception occurred in the class, so basically `removeTemporaryFiles` is not called and you can have a lot of unnecessary files.

I think there are several way to fix that:

* I think we should handle this manually in `checkProcessStatus` and `checkOutput` methods (call `$this->removeTemporaryFiles();` manually).
* create a custom Exception and pass the Pdf as argument to call `removeTemporaryFiles` ;
* or try through `set_exception_handler` or `register_shutdown_function` to handle that...

What do you think about that and what should be a good solution for you?

**Comment by akovalyov** [comment]
I'd vote for ```register_shutdown_function``` because it is the only way to handle unexpected behaviour since:
1. Exception can be thrown in code after snappy has rendered the pdf/image, so in this case we won't be able to catch it. So, ```set_error_handler``` or ```register_shutdown_function``` at the moment.
2. If there is an error of level E_FATAL, we won't be able to catch it but we still need to make a cleanup, so only ```register_shutdown_function``` can work well here IMO.
