### ISSUE TITLE
Blank pdf when minified html

### ISSUE THREAD

**Issue by ogrosko** [KnpLabs/snappy#212]
When I use minify html for my site and generate pdf from it I get only blank pdf.
using `./wkhtmltopdf-amd64` from bash it works

**Comment by MarwanEB** [comment]
Hello !
I had the exactly the same problem (with version 0.12.3). When I try to do it from my server, I get those logs :
```bash
wkhtmltopdf --load-error-handling ignore http://mypage.com test.pdf
```
```bash
Loading pages (1/6)
Warning: Failed loading page http://mypage.com (ignored)
Counting pages (2/6)
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to network error: HostNotFoundError
```

**Comment by ogrosko** [comment]
I solve it by excluding page from minifying (In my case only one page)

**Comment by akovalyov** [comment]
@MarwanEB is `mypage.com` just an example or you using that domain in your code?

**Comment by akovalyov** [comment]
@ogrosko without any code examples it is hard to say. 
However, I believe that it is something not related to snappy, since we don't do any html preprocessing (except saving remove html pages as local ones to have workaround over remote html in headers/footers). Probably, your minifier just strips too much. 

So, I suggest to check the minified output and validate is with [W3C validator](https://validator.w3.org/). If it is valid and still wkhtmltopdf doesn't work - you might create an issue in https://github.com/wkhtmltopdf/wkhtmltopdf
