### ISSUE TITLE
Cannot use calc() CSS function

### ISSUE THREAD

**Issue by eossa** [KnpLabs/snappy#220]
```
<td style="width: calc(100%/4)">Ipsum1</td>
<td style="width: calc(100%/4)">Ipsum2</td>
<td style="width: calc(100%/4)">Ipsum3</td>
<td style="width: calc(100%/4)">Ipsum4</td>
```

The width is not the correct.

**Comment by MitchellBouwman** [comment]
Just do `width: 25%`? Calc needs rendering time which is not possible since the pdf generator starts immediately and skips your calc part to be done as soon as possible.

**Comment by daudmalik06** [comment]
@eossa i had some issue with wkhtmltopdf too for this purpose born new library which uses chrome headless as a back-end so no more these kind of problems try this 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by NiR-** [comment]
In fact I don't think this is about timing as suggested by @MitchellBouwman: even with a high value for `--javascript-delay` (let's say 2000) it does not work. Based on [QtWebkit documentation](http://doc.qt.io/qt-4.8/qtwebkit-guide.html#qtwebkit-2-1-for-web-developers), I rather think that `calc` is not supported at all by the version of Webkit used.

Since this is not directly related to snappy but to wkhtmltopdf and its underlying Webkit version, I close this issue. Feel free to ping me if you think there's something to do on snappy side.

**Comment by jonnylink** [comment]
This is a pretty big bummer since there are many other uses of `calc()` that can't be solved simply by using a straight percent.

**Comment by jonnylink** [comment]
Looks to me like wkhtmltopdf does support `calc()` since it is mentioned explicitly in some of the commits: https://github.com/wkhtmltopdf/qtwebkit/commits/wk_master
