### ISSUE TITLE
Generate Image

### ISSUE THREAD

**Issue by virajshah25** [KnpLabs/snappy#242]
I am trying to generate image from html and sending that image as attachment in email. The html from which  i am generating image has jquery code in it. jQuery code generates popovers on image but after generating image popovers don't appears on same position.

**Comment by NiR-** [comment]
> jQuery code generates popovers on image but after generating image popovers don't appears on same position.

Do you mean that at some time the popover is rightly positioned but after some js code does its job the popover is wrongly positioned?

Do you have any xvfb set up? It might be a screen resolution problem and [like the faq suggests](https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#q-my-pdf-is-always-generated-for-a-small-screen-resolutioni-always-receive-a-mobile-version), for such a case, you need to set xvfb up. Or you can use the little css trick suggested.

Also I'm not sure if this bug is related to snappy itself or rather wkhtmltopdf. Did you tried to dump the command executed by snappy and run it by hand to see what happens? If you don't know how to do [the faq](https://github.com/KnpLabs/snappy/blob/master/doc/faq.md) will help you.
You can also enable `debug-javascript` option and add some `console.log` to your javascript code. It's a poor solution, but it can help...

**Comment by NiR-** [comment]
Please @virajshah25 answer my questions. If you don't provide any feedback before the end of the week I'll close this issue.
