### ISSUE TITLE
Loss of URL-encoded characters during PDF generation

### ISSUE THREAD

**Issue by TomPeters-NL** [KnpLabs/snappy#356]
Hey all,

I seem to be losing some url-encoded characters when calling `getOutput()`.

```
wkhtmltopdf https://www.google.com/search?q=snappy%2Bknplabs%2Cphp GoogleSearch.pdf
```
A direct command (shown above) results in a PDF with the Google search results for `snappy+knplabs,php`.

```
$snappyUrl = 'https://www.google.com/search?q=snappy%2Bknplabs%2Cphp';
return $this->pdf->getOutput($snappyUrl);
```
Yet, when I attempt the same in PHP (shown above), the generated PDF is for `snappy 2Bknplabs 2Cphp`.

OS: Windows 10 Home 1803
Wkhtmltopdf: `wemersonjanuario/wkhtmltopdf-windows v0.12.2.3` via Composer

Is anyone familiar with this and whether this is a bug, or whether I'm just missing something obvious?

Cheers!

**Comment by alexpozzi** [comment]
Hello,
Unfortunately I'm not able to replicate the issue you described but I can't test it on Windows.
I'm afraid this issue is related to `escapeshellarg` function that, on Windows, replaces `%`s with spaces (see [here](https://www.php.net/manual/en/function.escapeshellarg.php) and [here](https://www.php.net/manual/en/function.escapeshellarg.php#84789)).
This library uses this function to escape arguments and options before running the wkhtmltopdf command.
Did you try with a non encoded url like `https://www.google.com/search?q=snappy+knplabs,php`?
