### ISSUE TITLE
Issue with high CPU

### ISSUE THREAD

**Issue by benjamin2k** [KnpLabs/snappy#402]
Hello Everyone.

I hope this problem is not a doublon, i can't find any working solution for my web application.

When I generate PDF i get sometime this error. I think this is because they are 2 pdf generation a the same time, and the CPU is around 100%. It may crash the script.

Can someone explain the "127" status code ?

Thanks for your support 
Benjamin

I am using : 
knplabs/knp-snappy, version 0.4.3
h4cc/wkhtmltopdf-amd64, version 0.12.4

$snappy = new Pdf('/usr/bin/xvfb-run /usr/bin/wkhtmltopdf');
$snappy->setOption('page-size', 'A4');
$snappy->setOption('dpi', '144');
$snappy->setOption('zoom', '1');
$snappy->setOption('margin-left', '0mm');
$snappy->setOption('margin-right', '0mm');
$snappy->setOption('margin-top', '0mm');
$snappy->setOption('margin-bottom', '0mm');

Fatal error: Uncaught RuntimeException: The exit status code '127' says something went wrong: stderr: "/usr/bin/xvfb-run: line 180: fmt: not found sh: write error: Broken pipe " stdout: "" command: /usr/bin/xvfb-run /usr/bin/wkhtmltopdf --lowquality --dpi '144' --margin-bottom '0mm' --margin-left '0mm' --margin-right '0mm' --margin-top '0mm' --page-size 'A4' --zoom '1' '/tmp/knp_snappy5f4534d545beb8.13941753.html' '/var/www/html/public/uploads/tickets/351698/xxx.pdf'. in /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:336 Stack trace: #0 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(151): Knp\Snappy\AbstractGenerator->checkProcessStatus(127, '', '/usr/bin/xvfb-r...', '/usr/bin/xvfb-r...') #1 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(62): Knp\Snappy\AbstractGenerator->generate(Array, '/var/www/html/p...', Array, false) #2 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(170): in /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php on line 336

**Comment by alexpozzi** [comment]
I would suggest you to test the failing commands manually to see if it's related to specific pages or not.
I don't think that's the problem but it seems you have a missing dependency (see `/usr/bin/xvfb-run: line 180: fmt: not found`) and, fixing it, might give more details about the error.

You can also have a look at this issue https://github.com/barryvdh/laravel-snappy/issues/68 (hope it will help you).

These are just guesses as it's not easy to find a solution for non-replicable issues.

I'm closing the issue here because there is nothing more I can do.
If you'll find a solution or if you'll get more details please reply to this issue as it might help others in the future.
