### ISSUE TITLE
Centos7 render font error

### ISSUE THREAD

**Issue by randomHHH** [KnpLabs/snappy#407]
system version: CentOS Linux release 7.3.1611 (Core)
wkh version:  wkhtmltopdf 0.12.6 (with patched qt)

i use rpm -ivh wkhtmltox-0.12.6-1.centos7.x86_64.rpm  to install 

I had install this packages:
    xorg-x11-server-Xvfb
    xorg-x11-fonts-Type1
    xorg-x11-fonts-75dpi
    dejavu-sans-fonts
    urw-fonts

![image](https://user-images.githubusercontent.com/20147474/99767407-f21e3f00-2b3d-11eb-9e8b-49de56c65b4e.png)

**Comment by randomHHH** [comment]
![image](https://user-images.githubusercontent.com/20147474/99767812-9b653500-2b3e-11eb-9749-3f16e6b7ad5e.png)

i want to render  to like  this

**Comment by alexpozzi** [comment]
This issues is a wkhtmltopdf issue and I think you will have more luck to open an issue on [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) repository (there are already similar issues opened https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4879, https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4863 and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4836 for example).
By experience I can tell you that you are probably missing the necessary font (or not loading it correctly) on your server and, in order to fix the issue, you should install it/check why it's not loaded.
If you try to launch the pdf generation from the command line using wkhtmltopdf command you'll probably be able to get more information about the failure.

I'm closing the issue as this is not a Snappy issue.
