### ISSUE TITLE
HELP! Any option to set different cover page margins.

### ISSUE THREAD

**Issue by mohsinalandsterling** [KnpLabs/snappy#418]
Is there any way to set the different (from other pages) margin on the cover page?

Something like:
```
 $pdf_report->setOption('cover-margin-bottom', '0mm');
```

or 

```
 $pdf_report->setCoverOption('margin-bottom', '0mm');
```

**Comment by alexpozzi** [comment]
I'm afraid wkhtmltopdf does not support that.
If I remember correctly it supports global margin options only (see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt).
In order to achieve what you want to do you might have to generate two different PDFs (cover and content) and merge them after with utilities like Ghostscript.

**Comment by mohsinalandsterling** [comment]
Its mentions in here (https://wkhtmltopdf.org/usage/wkhtmltopdf.txt) in docs.

```
  cover <input url/file name> [PAGE OPTION]...
  All options that can be specified for a page object can also be specified for
  a cover.
```

So, it means the margin option should be available as well.

**Comment by alexpozzi** [comment]
Margins are part of the global options not page options and if I remember correctly you can't assign global options to a specific page.
By the way Snappy doesn't support multiple page options yet, at the moment you can just specify global page options.
