### ISSUE TITLE
Set global margin on PDF document

### ISSUE THREAD

**Issue by fredleput** [KnpLabs/snappy#420]
Hi,

First of all thx for this wonderful library, she works great (also with multi pages PDF documents which is not the case of other libraries i tested). She's also able to understand complex css properties like position relative and position absolute, fonts, negative margins... (better than than IE did).

Here is my question : I'm sure it's quite simple to do but i didn't succeed : **how to reduce global margins of the document ? (sorry i didn't found on google)**

I tried 2 things :

- first in my inline css : body { margin-left: -10mm; margin-right: -10mm; } // did not work (i hope it's not symfony cache i cleared it before testing)
- i also tried : body: {margin 0}
- second : i have a global div with class name "pdf" and i tried in my inline css : .pdf { margin-left: -10mm; margin-right: -10mm;} did not work also

My environment : dedicated server (OVH) Debian 10, latest apache and latest wkhtml i installed by myself)

I'm surprised because every thing else works perfectly (and seems to be much more difficult)

Thx in advance,

Fred, Brittany - France.

**Comment by alexpozzi** [comment]
Hello Fred,
I think your issue is caused by the default margins (left/right) that `wkhtmltopdf` applies when generating the pdf (see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt).
In order to reduce the defuault 10mm margin you will just have to set the margin-left and margin-right options.
Let me know if it helps :wink:
