### ISSUE TITLE
PDF ENCODING Problem

### ISSUE THREAD

**Issue by boparaiamrit** [KnpLabs/snappy#70]
Not rendering text when i try to generate pdf
![file copy](https://f.cloud.github.com/assets/1220153/1217800/06f0bba0-26b0-11e3-818a-02222e7331f6.jpg)

**Comment by rodmarzavala** [comment]
ran the 3 commands but does not run me another idea?

**Comment by akovalyov** [comment]
@rodmarzavala 
1. you haven't provided any information about the OS you are using - whether it is Windows/Mac/Linux, if Linux - is it with yum/apt/pacman/etc package manager.
2. you haven't provided any information about what happens when you enter these commands.
3. we are neither mediums nor Google here.
4. we are not your OS support here.

Please, make comments with more sense in future if you want people help you. It doesn't matter whether you speak English well or not. In FOSS several lines of code, exception message, stack trace, logs etc often are more informative than user message.
Cheers.

**Comment by njuki** [comment]
@boparaiamrit solution did not work for me on oracle linux 7.2. However this did the magic:
`sudo yum install urw-fonts libXext openssl-devel`
