### ISSUE TITLE
Screen size for mobile version

### ISSUE THREAD

**Issue by zbychu555** [KnpLabs/snappy#87]
When I generated pdf I have always mobile version. Where can I set screen size? When I checked in javascript my screen and window size for pdf I have 640px for screen and 0px for windows width. I would like to have normal version (no mobile).

 I use foundation for responsive template.

**Comment by JD-Robbs** [comment]
I had the same issue and, apparently, the viewport-size setting in wkhtmltopdf can help:

I just tried adding 'viewport-size' => '1280x1024' inside the addOptions() call and inside the options parameter when instantiating \Knp\Snappy\Image. However, unfortunately, this makes it fail without a notice.

Would anyone know how this option can be added? Not sure, but maybe this option should be available within Snappy.

**Comment by akovalyov** [comment]
This issue is well-known for wkhtmltopdf - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1508. There are two possibilities to fix it, the first one is to setup xvbf to have the resolution that you want and the one which I haven't had a chance to try is https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1508#issuecomment-54284845.

For wkhtmltoimage there is no such an option, unfortunately.
