### ISSUE TITLE
How to use footer-html option?

### ISSUE THREAD

**Issue by divdax** [KnpLabs/snappy#97]
Hey guys,

i want to use footer in my dynamic generated pdf files with the footer-html option but it doesn't work.
Here is my code:

```
$footer = url('documents/pdf/footer'); // generate footer url (html output)
PDF::loadView('documents.pdf.offer', $data)->setOption('footer-html', $footer);
```

If i want to view my pdf i only get an error: Error on load pdf file. :(

When not set the option:

```
setOption('footer-html', $footer);
```

the pdf generations works fine.

**Comment by webdevilopers** [comment]
Thanks @divdax for this code snippet! I tried various examples from the net. Though my footer was always included it was always placed on top of the page and created a weird amount of pages and content.

The only thing that was missing and totally fixed everything was mentioning the doctype:
```html
<!doctype html>
```

Otherwise my pdf was messed up. Very strange behaviour. Can you confirm this issue?

**Comment by adil-kachbat** [comment]
You should also add the margin bottom for the page if the footer not shown
